### ISSUE TITLE
Investigate spacy lemmatiser in v.3.0

### ISSUE THREAD

**Issue by aCampello** [wellcometrust/WellcomeML#271]
Seem that v3.0 requires tagger, which makes it much slower. Maybe we can load the old look-up one

https://spacy.io/api/lemmatizer

**Comment by lizgzil** [comment]
I think we can replace https://github.com/wellcometrust/WellcomeML/blob/dbb71d863bca32890e703d44c1ffbbb680de760a/wellcomeml/ml/frequency_vectorizer.py#L86-L101

with 
```
nlp = spacy.blank("en")
nlp.add_pipe("lemmatizer", config={"mode": "lookup"})
nlp.initialize()
```
Which on 1000 grant descriptions took 37.5 secs with the current method (v1) and 2.1 secs with the new method (v2).

The performance is different between v1 and v2 when I looked at the output of one grant description - but I think there may actually be a bug since it doesn't look lemmatized in v1:
```
>>> set(v1_first_output).difference(set(v2_first_output))
{'underrepresented', 'included', 'remaining', 'organisations', 'recruited', 'backgrounds', 'greater', 'priorities', 'includes', 'disadvantaged', 'wishes', 'depending', 'years', 'located', 'indicates', 'funds', 'graduates', 'achieving', 'living', 'groups', 'students', 'expenses', 'recommended'}
>>> set(v2_first_output).difference(set(v1_first_output))
{'depend', 'achieve', 'underrepresent', 'recommend', 'university', 'priority', 'include', 'graduate', 'remain', 'organisation', 'fund', 'student', 'indicate', 'locate', 'wish', 'expense', 'great', 'live', 'disadvantage'}
```
Happy to make this change
