### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by nsorros** [wellcometrust/WellcomeML#97]
At the moment we do not enforce any code style even though we loosely follow the [Google python style code ](https://google.github.io/styleguide/pyguide.html). 

The most commonly used code style revolves around pep8/flake8. There are two different workflows we can follow

- install some way of nagging us towards conforming to pep8/flake8
- install an automatic code formatter like [black](https://github.com/psf/black) that follows the above

The benefit of the first is that over time you learn to write better code and not produce corrections according to pep8 / flake8. The benefit of the second is that formatting is automated and taken care of.

If we choose the first option we have two different means of enforcing it.

1. Adding a check in Github similar to build and codecov for example [this](https://github.com/marketplace/actions/run-flake8-on-your-pr-with-annotations).
2. Adding a [pre commit hook](https://git-scm.com/book/en/v2/Customizing-Git-Git-Hooks) that checks and does not allow you to commit code if it does not conform.

The second is quite annoying so I would be in favour of the first if possible. I am indifferent on whether we use black or pep8 /flake8 explicitly. Let me know what you think.

**Comment by lizgzil** [comment]
I think I'm more on the side of being nagged to format properly rather than automatic changes for the benefit of learning better like you say.

Looks like you can use Black in the CI (https://www.mattlayman.com/blog/2018/python-code-black/) :

"
... Black has a mode that directly supports CI checking!
```
$ black --check my_package/
would reformat /Users/matt/projects/my_package/some_file.py
All done! 💥 💔 💥
1 file would be reformatted, 107 files would be left unchanged.
```
"If you add Black to a CI build process with the --check option, the tool will report any code that does not adhere to the code format and fail the CI build. This may not sound like a good thing, but it is!"

So I guess this means it will nag you from the failed CI, but not sure if it specifically shows you what you need to change

**Comment by nsorros** [comment]
Waiting to hear @aCampello thoughts as well. If there is a consecus on running checks vs automatically formatting the code, I will start implementing either what you suggested @lizgzil or a pep8 / flake8 check like the one I mention above.

**Comment by aCampello** [comment]
Adding a check in GitHub is my preferred option as well. You can probably add `flake8` as a command to the pipeline. I wouldn't like this to block us from merging or committing, but otherwise would be good to comply with the norms. We can start by running it locally and creating a checkbox-style issue for those.
